services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: messagesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    ports:
      - "3306:3306"

  flask-app:
    build:
      context: .
    container_name: my-flask-app
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql-db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: messagesdb
    networks:
      - my-network
    ports:
      - "5000:5000"

networks:
  my-network:

volumes:
  mysql-data:
